---
name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - run: go test -v -race -coverprofile=coverage.txt ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1 # renovate: datasource=github-releases depName=golangci/golangci-lint

          # In general linting is quite fast with warm caches, but a fresh run might take some time.
          args: --timeout 5m
